### ISSUE TITLE
Package works well for debug.apk but when i built release apk then its not working

### ISSUE THREAD

**Issue by rohit0407org** [alanmosely/esp_provisioning_wifi#2]
spBleProv(18099): scanNetworks: error java.lang.RuntimeException: Failed to create session.
( 18899): [ERROR: Flutter/runtime/dart.vn_initializer.cc(41)] Unhandled Exception: PlatformException(E1, WiFi scan failed, Exception details java.lang.RuntimeException: Failed to create session., null) (18899):#0 StandardMethodCodec,decodeEnvelope (package: flutter/arc/services/message.codecs.dart:648) (18899 ): #1 MethodChannel. invokeMethod (package:flutter/src/services/platform channel.dart:334) ( 18899): casynchronous suspension 18099): #2 MethodChannelFlutterEspBleProv.scanßifiNetworks (package:flutter esp ble prov/src/flutter esp ble prov method channel.dart:38) ( (18899): <asynchronous suspension> 18899): #3 ( WifiConnectionPageState.scanilifiNetworks (package: lot prov new 11b/wifi.connection page.dart:33) (18899): <asynchronous suspension> Futter Performance Hatter Outline
I have updated both build.gradle as per documentation tooo

Please help me its too urgent

![issue](https://github.com/user-attachments/assets/cfce2734-450d-4fc1-b2b0-efae078bf8d0)
![manifest](https://github.com/user-attachments/assets/045b0859-27a0-44af-b45b-7570dfabaa84)

**Comment by alanmosely** [comment]
Hi Rohit, please provide a minimal reproducible sample that shows the problem and the full output of running `flutter doctor -v`

**Comment by alessandrv** [comment]
I'm having same issues running example app with flutter run --release, no wifi gets found

**Comment by rohit0407org** [comment]
I think i got the solution 

make a proguard-rules.pro file in android--> app-->proguard-rules.pro
proguard-rules.pro
# The espressif library needs to have all their names and fields preserved.
-keep,allowoptimization class espressif.* { *; }


then register proguard-rules.pro in android-->app--->build.gradle

buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
            minifyEnabled true // Ensure this is true for release builds
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'


        }
    }
    
    then issue is solved
